//generated by Gemini
export function getMonthNameAfterXDays(daysToAdd: number): string {
  const futureDate = new Date();
  futureDate.setDate(futureDate.getDate() + daysToAdd);
  
  return futureDate.toLocaleString('en-US', { month: 'long' });
}

export function getDayAfterXDays(daysToAdd: number): string {
  const date = new Date();
  date.setDate(date.getDate() + daysToAdd);
  
  return date.toDateString();
}

export function getCustomDateFormatWithShortMonthAfterXDays(daysToAdd: number): string {
  const date = new Date();
  date.setDate(date.getDate() + daysToAdd);

  const day = date.getDate();
  const month = date.toLocaleString('en-US', { month: 'short' });
  const year = date.getFullYear();

  return `${day} ${month} ${year}`;
}

export function getDayOfWeekAfterXDays(daysToAdd: number): string {
  const date = new Date();
  date.setDate(date.getDate() + daysToAdd);
  
  return date.toLocaleString('en-US', { weekday: 'long' });
}